package jjcard.textGames.game.impl;

public enum ReturnCom {
	GOT_ITEM, GOT_ITEM_NOT_FOUND, LOOK_ROOM, COMMAND_NOT_FOUND, LOOK_PLAYER, LOOK_MOB, LOOK_MOB_NOT_FOUND, LOOK_ITEM, LOOK_ITEM_NOT_FOUND, LOOK_NOT_FOUND, ATTACK_MOB, ATTACK_MOB_NOT_FOUND, ATTACK_MOB_KILLED,
	MOVED_NORTH, MOVED_SOUTH, MOVED_EAST, MOVED_WEST, MOVED_DIRECTION, MOVED_NOT_FOUND, INFO_HEALTH, INFO_INVENTORY, INFO_INVENTORY_EMPTY, INFO_MONEY, INFO_MAX_HEALTH, INFO_NOT_FOUND, INFO_PLAYER_ITEM,
	GOT_ITEM_UNMOVED, LOOT_MOB, LOOT_MOB_NOT_FOUND, LOOT_MOB_ALIVE, ITEM_DROPPED, DROP_ITEM_NOT_FOUND, EQUIPPED_WEAPON, EQUIPPED_ARMOUR, EQUIPPED_NOT_FOUND, UNEQUIPPED_WEAPON, UNEQUIPPED_ARMOUR, 
	UNEQUIPPED_ITEM_NOT_FOUND, UNEQUIPPED_NO_WEAPON, UNEQUIPPED_NO_ARMOUR;
}
